name: Build & Test

on:
  push:
    branches: [ main ]
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  build-and-test:
    runs-on: macos-latest
    timeout-minutes: 40

    env:
      SCHEME: RunningDiary
      PROJECT: RunningDiary.xcodeproj
      DESTINATION: "platform=iOS Simulator,name=iPhone 17,OS=18.0"

    steps:
      - uses: actions/checkout@v4
      - name: Start xcode build 🛠
        run: |
          xcodebuild clean test -project "$PROJECT" -scheme "$SCHEME" -destination "$DESTINATION" -enableCodeCoverage YES
