name: Build & Test

on:
  push:
    branches: [ main ]
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  build-and-test:
    runs-on: macos-latest
    timeout-minutes: 40

    env:
      SCHEME: RunDiary
      PROJECT: RunDiary.xcodeproj
      DESTINATION: "platform=iOS Simulator,name=iPhone 17 Pro,OS=latest"

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '26'
          
      - name: Start xcode build 🛠
        run: |
          xcodebuild clean test -project "$PROJECT" -scheme "$SCHEME" -destination "$DESTINATION" -enableCodeCoverage YES -skipMacroValidation ENABLE_SWIFT_MACROS=YES
